Handle utterly fucked constant in the RS690 code.
../../../../dev/pci/drm/radeon/rs690.c:308:29: error: signed shift result
      (0x11A49A00000) requires 42 bits to represent, but 'int' only has 32 bits
      [-Werror,-Wshift-overflow]
                read_delay_latency.full = dfixed_const(370 * 800 * 1000);
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../dev/pci/drm/drm_fixed.h:33:36: note: expanded from macro
      'dfixed_const'

We do as FreeBSD did here and replace that with the (obviously wrong)
UINT_MAX. Add large comment explaining why for now.